# substrate-save
# deployment.template.yml
#
# use:
# envsubst < deployment.template.yml | kubectl apply -f -
#
# the following variables have to be set:
#
# SUBSTRATE_SAVE_DB_URL postgres://username:password@localhost/save
# WS_PORT can be 1024
# REPLICAS
# SUBSTRATE_SAVE_DOCKER_IMAGE
# 
# HEARTBEAT_INTERVAL
# CLIENT_TIMEOUT
# PURGE_FREQUENCY
# LOG_EXPIRY_HOURS
# MAX_PENDING_CONNECTIONS
# DATABASE_POOL_SIZE
# LOG_EXPIRY_HOURS
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: substrate-save
  namespace: $NAMESPACE
spec:
  selector:
    matchLabels:
      app: substrate-save

  replicas: $REPLICAS
  revisionHistoryLimit: 2
  minReadySeconds: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  template:
    metadata:
      labels:
        app: substrate-save

    spec:
      containers:
        - name: substrate-save
          image: $SUBSTRATE_SAVE_DOCKER_IMAGE
          imagePullPolicy: Always
          # command: ["/bin/sh"]
          # args:
          #   - "-x"
          #   - "-c"
          #   - >
          #     sleep 600
          ports:
          - containerPort: $WS_PORT
          env:
            - name: DATABASE_URL
              value: "$SUBSTRATE_SAVE_DB_URL"
          envFrom:
            - configMapRef:
                name: substrate-save
          readinessProbe:
            tcpSocket:
              port: $WS_PORT
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: $WS_PORT
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: substrate-save
  namespace: $NAMESPACE
data:
  PORT: "$WS_PORT"
  HEARTBEAT_INTERVAL: "$HEARTBEAT_INTERVAL"
  CLIENT_TIMEOUT: "$CLIENT_TIMEOUT"
  PURGE_FREQUENCY: "$PURGE_FREQUENCY"
  LOG_EXPIRY_HOURS: "$LOG_EXPIRY_HOURS"
  MAX_PENDING_CONNECTIONS: "$MAX_PENDING_CONNECTIONS"
  DATABASE_POOL_SIZE: "$DATABASE_POOL_SIZE"
  LOG_EXPIRY_HOURS: "$SAVE_LOG_EXPIRY_HOURS"
  RUST_LOG: "$SAVE_RUST_LOG"
---
apiVersion: v1
kind: Service
metadata:
  name: substrate-save
  namespace: $NAMESPACE
spec:
  selector:
    app: substrate-save
  ports:
    - name: ws
      port: $WS_PORT
      targetPort: $WS_PORT
      protocol: TCP
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 35.198.174.150/32 # test-machine
  - 212.227.252.235/32 # vpn-server
  - 35.246.224.91/32 # substrate20-0
  - 35.246.210.11/32 # substrate20-1
  - 35.198.110.45/32 # substrate20-2
  - 35.198.114.154/32 # substrate20-3
  - 51.77.66.187/32 # kusama-bootnode-0
  - 51.79.17.206/32 # kusama-bootnode-1
